apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ template "prometheus.name" . }}
  labels:
    {{- include "eventstats.prometheus.labels" . | nindent 4 }}

data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: '{{ template "watcher.name" . }}'
        static_configs:
            - targets: ['{{ template "watcher.name" .  }}']

