apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ template "reporter.name" . }}
  labels:
    {{- include "eventstats.reporter.labels" . | nindent 4 }}

data:
  REP_SMTP_USER_PASSWORD: {{ .Values.reporter.envsec.REP_SMTP_USER_PASSWORD | b64enc | quote }}
