apiVersion: v1
kind: Service

metadata:
  name: {{ template "watcher.name" . }}
  labels:
    {{- include "eventstats.watcher.labels" . | nindent 4 }}

spec:
  selector:
    {{- include "eventstats.watcher.labels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 10080
      protocol: TCP
      name: http
